if (-not $options) {
	$options = [ordered] @{ }
}

# Global options
$options['__'] = @(
	'-v',
	'--version',
	'--no-default-rc',
	'--use-yarnrc',
	'--verbose',
	'--offline',
	'--prefer-offline',
	'--enable-pnp',
	'--pnp',
	'--disable-pnp',
	'--strict-semver',
	'--json',
	'--ignore-scripts',
	'--har',
	'--ignore-platform',
	'--ignore-engines',
	'--ignore-optional',
	'--force',
	'--skip-integrity-check',
	'--check-files',
	'--no-bin-links',
	'--flat',
	'--prod',
	'--production',
	'--no-lockfile',
	'--pure-lockfile',
	'--frozen-lockfile',
	'--update-checksums',
	'--link-duplicates',
	'--link-folder',
	'--global-folder',
	'--modules-folder',
	'--preferred-cache-folder',
	'--cache-folder',
	'--mutex',
	'--emoji',
	'-s',
	'--silent',
	'--cwd',
	'--proxy',
	'--https-proxy',
	'--registry',
	'--no-progress',
	'--network-concurrency',
	'--network-timeout',
	'--non-interactive',
	'--scripts-prepend-node-path',
	'--no-node-version-check',
	'--focus',
	'--otp'
)
